### ISSUE TITLE
bt-host.h not in the qemu sdk

### ISSUE THREAD

**Issue by causten** [openbmc/btbridge#1]
$ make
arm-openbmc-linux-gnueabi-gcc  -march=armv5e -marm  -mthumb-interwork --sysroot=/opt/openbmc-phosphor/1.8+snapshot/sysroots/armv5e-openbmc-linux-gnueabi  -O2 -pipe -g -feliminate-unused-debug-types `pkg-config --cflags --libs libsystemd` btbridged.c -o btbridged
btbridged.c:33:27: fatal error: linux/bt-host.h: No such file or directory
 #include <linux/bt-host.h>
                           ^
compilation terminated.

Running bitbake -c populate_sdk obmc-phosphor-image doesn't get it in the build

**Comment by williamspatrick** [comment]
This is because qemu doesn't use the kernel that has the bt driver.

If we are trying to build btbridge in the qemuarm machine, we are doing
something wrong and we need to fix the openbmc recipe.

On Thu, Oct 29, 2015 at 11:55:22AM -0700, Chris Austen wrote:

> $ make
> arm-openbmc-linux-gnueabi-gcc  -march=armv5e -marm  -mthumb-interwork --sysroot=/opt/openbmc-phosphor/1.8+snapshot/sysroots/armv5e-openbmc-linux-gnueabi  -O2 -pipe -g -feliminate-unused-debug-types `pkg-config --cflags --libs libsystemd` btbridged.c -o btbridged
> btbridged.c:33:27: fatal error: linux/bt-host.h: No such file or directory
>  #include <linux/bt-host.h>
>                            ^
> compilation terminated.
> 
> Running bitbake -c populate_sdk obmc-phosphor-image doesn't get it in the build
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openbmc/btbridge/issues/1

## 

Patrick Williams

**Comment by williamspatrick** [comment]
Please open an issue under openbmc/openbmc instead.  This isn't a btbridge issue itself.
