### ISSUE TITLE
Header (linux/bt-host.h) missing within SDK build

### ISSUE THREAD

**Issue by msbarth** [openbmc/btbridge#13]
The btbridge package fails to compile within a SDK where it seems the missing header files (linux/bt-host.h) is downloaded, using `wget` from a site and placed locally to successfully build. This was determined from the .build.sh file within this repo.

Moving forward with converting this package over to use of autotools needs to have this package able to be built within a standalone SDK.

**Comment by shenki** [comment]
The build.sh wgets the file as a hack so CI systems such as Travis CI can build the tool without requiring a new Linux kernel headers package to be installed.

The correct way of building this is to have a version of the kernel headers installed that contains this file.

**Comment by williamspatrick** [comment]
SDK builds aren't recommended anymore.  I think this is resolved since bt-host is part of the OS kernel headers now.
